name: Build and Deploy with Git Subtree

on:
  workflow_dispatch:  # Permette di avviare manualmente il workflow
  push:
    branches:
      - develop  # Cambia se vuoi attivare il workflow da un altro branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout del repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      # 3️⃣ Installazione dipendenze
      - name: Install Dependencies
        run: npm install

      # 4️⃣ Build del progetto (genera la cartella dist)
      - name: Build Project
        run: npm run build

      # 5️⃣ Commit della directory dist (se necessario)
      - name: Commit dist folder to repository
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Assicura che dist/ sia tracciato
          git add dist
          git commit -m "Update dist subtree" || echo "No changes in dist to commit"

      # 6️⃣ Deploy della cartella dist/ su gh-pages usando git subtree
      - name: Deploy to GitHub Pages using git subtree
        run: |
          git push origin `git subtree split --prefix dist master`:gh-pages --force
